% ExtAndRangeGUI -- dialog for output filetype and frame range. 0=cancel.
function [startframe,endframe,filetype,scaling] =...
    ExtAndRangeGUI(numframes, inExt)
% filetypes: '.avi','.tif','.jpg'
% scaling: 'moviemax','framemax','shift5','shift4','none'

% frame range and file type figure window
    hExtAndRangeFig = figure('MenuBar','none', 'Toolbar','none', ...
        'HandleVisibility', 'callback', ...
        'Position', [190,500,360,420], ...
        'Name', 'Output Type and Range', ...
        'NumberTitle','off', ...
        'Color', get(0,'defaultuicontrolbackgroundcolor'), ...
        'CloseRequestFcn',@my_closereq, ...
        'Userdata',1);

    hstartlabel = uicontrol('Parent', hExtAndRangeFig, 'Style', 'text', ...
        'Units', 'characters', 'Position',[5 25 15 1.5],...
        'FontSize',10, ...
        'String','Start Frame: ', ...
        'BackgroundColor',get(0,'defaultuicontrolbackgroundcolor'), ...
        'HorizontalAlignment','right');
    hstart = uicontrol('Parent', hExtAndRangeFig, 'Style', 'edit', ...
        'Units', 'characters', 'Position',[20 25 15 1.5],...
        'FontSize',10, ...
        'Min',1,...
        'Max',numframes,...
        'Callback',@hstartCallback, ...
        'BackgroundColor',[1,1,1], ...
        'String','1', ...
        'Value', 1);
    hfinishlabel = uicontrol('Parent', hExtAndRangeFig, 'Style', 'text', ...
        'Units', 'characters', 'Position',[5 23 15 1.5],...
        'String','End Frame: ', ...
        'FontSize',10, ...
        'BackgroundColor',get(0,'defaultuicontrolbackgroundcolor'), ...
        'HorizontalAlignment','right');
    hfinish = uicontrol('Parent', hExtAndRangeFig, 'Style', 'edit', ...
        'Units', 'characters', 'Position',[20 23 15 1.5],...
        'FontSize',10, ...
        'Min',1, ...,
        'Max', numframes, ...
        'Callback',@hfinishCallback, ...
        'BackgroundColor',[1,1,1], ...
        'String',num2str(numframes,'%d'), ...
        'Value', numframes);

    hfilelabel = uicontrol('Parent',hExtAndRangeFig,'Style','text', ...
        'Units', 'characters', 'Position',[5 20 15 1.5],...
        'String', 'Output Type:', ...
        'FontSize',10, ...
        'HorizontalAlignment','right', ...
        'BackgroundColor',get(0,'defaultuicontrolbackgroundcolor'));
 
    hButtons = uibuttongroup('Parent',hExtAndRangeFig, ...
        'visible','off',...
       'Userdata',['.avi']);
 
    haviradio = uicontrol('Parent',hButtons,...
        'Style','Radio', ...
        'Units', 'characters', 'Position',[22 20 15 1.5],...
        'FontSize',10, ...
        'String','avi file', ...
        'HandleVisibility','off', ...
        'Tag','.avi',...
        'Enable','off', ...
        'Value',0);
   htifradio = uicontrol('Parent',hButtons,...
        'Style','Radio', ...
        'Units', 'characters', 'Position',[22 18.5 25 1.5],...
        'FontSize',10, ...
        'String','(stack of) tif file(s)', ...
        'HandleVisibility','off', ...
        'Tag','.tif',...
        'Value',0);
    hjpgradio = uicontrol('Parent',hButtons,...
        'Style','Radio', ...
        'Units', 'characters', 'Position',[22 17 30 1.5],...
        'FontSize',10, ...
        'String','(stack of) jpg file(s)', ...
        'HandleVisibility','off',...
        'Tag','.jpg',...
        'Value',0);
    
    hscalelabel = uicontrol('Parent',hExtAndRangeFig,'Style','text', ...
        'Units', 'characters', 'Position',[1 13 19 1.5],...
        'String', 'Output Scaling:', ...
        'FontSize',10, ...
        'HorizontalAlignment','right', ...
        'BackgroundColor',get(0,'defaultuicontrolbackgroundcolor'));
    
    hscaleButtons = uibuttongroup('Parent',hExtAndRangeFig,...
                'visible','off',...
       'Userdata', ['moviemax']);
    
    hscale1radio = uicontrol('Parent',hscaleButtons,...
        'Style','Radio', ...
        'Units', 'characters', 'Position',[22 13 30 1.5],...
        'FontSize',10, ...
        'String','max. for file -> 255', ...
        'HandleVisibility','off',...
        'Tag','moviemax',...
        'Value',1);
    hscale2radio = uicontrol('Parent',hscaleButtons,...
        'Style','Radio', ...
        'Units', 'characters', 'Position',[22 11.5 35 1.5],...
        'FontSize',10, ...
        'String','max. for each frame -> 255', ...
        'HandleVisibility','off',...
        'Tag','framemax',...
        'Value',0);
    hscale3radio = uicontrol('Parent',hscaleButtons,...
        'Style','Radio', ...
        'Units', 'characters', 'Position',[22 10 30 1.5],...
        'FontSize',10, ...
        'String','shift -4', ...
        'HandleVisibility','off',...
        'Tag','shift4',...
        'Value',0);
    hscale4radio = uicontrol('Parent',hscaleButtons,...
        'Style','Radio', ...
        'Units', 'characters', 'Position',[22 8.5 30 1.5],...
        'FontSize',10, ...
        'String','shift -5', ...
        'HandleVisibility','off',...
        'Tag','shift5',...
        'Value',0);
    hscale5radio = uicontrol('Parent',hscaleButtons,...
        'Style','Radio', ...
        'Units', 'characters', 'Position',[22 7 30 1.5],...
        'FontSize',10, ...
        'String','none', ...
        'HandleVisibility','off',...
        'Tag','none',...
        'Value',0);
    
        scalingradio = hscale1radio;
        set(hscale1radio,'Value',1);
        set(hscale2radio,'Value',0);
        set(hscale3radio,'Value',0);
        set(hscale4radio,'Value',0);
        set(hscale4radio,'Value',0);
        set(hscaleButtons,'UserData','moviemax');
        
        typeradio = haviradio;
        set(haviradio,'Value',1);
        set(haviradio,'Enable','on');
        set(htifradio,'Value',0);
        set(hjpgradio,'Value',0);

    if strcmp(inExt,'.tif')
        typeradio = htifradio;
        set(htifradio,'Value',1);
        set(hButtons,'UserData','.tif');
    end
    if strcmp(inExt,'.jpg')
        typeradio = hjpgradio;
        set(hjpgradio,'Value',1);
        set(hButtons,'UserData','.jpg');
    end

   set(hButtons,'SelectionChangeFcn',@selcbk);
   set(hButtons,'SelectedObject',typeradio);  % No selection
   set(hButtons,'Visible','on');

   set(hscaleButtons,'SelectionChangeFcn',@selcbk1);
   set(hscaleButtons,'SelectedObject',scalingradio);  % No selection
   set(hscaleButtons,'Visible','on');
   
   set(hscalelabel,'Visible','off'); % disable feature
   set(hscaleButtons,'Visible','off'); % disable feature; output will be
                        % 8-bit samples scaled so movie maximum is 255.
   
   hContinueButton = uicontrol('Parent',hExtAndRangeFig,'Style','pushbutton', ...
       'Units','characters',...
       'Position',[20 5 15 2], ...
       'String','Continue',...
       'Callback','uiresume(gcbf)');

   uiwait(hExtAndRangeFig);
   
   set(hExtAndRangeFig,'CloseRequestFcn','closereq'); % restore default fcn
   startframe = get(hstart,'Value');
   endframe = get(hfinish,'Value');
   filetype = get(hButtons,'Userdata');
   scaling = get(hscaleButtons,'Userdata');
   close(hExtAndRangeFig);
  
return;
end

% -------------------------------------------------------------------------
% hstartCallback -- start frame edit box function. Display new value,
% update "value" field.
function hstartCallback(src,evnt)

startmin = get(src,'Min');
startmax = get(src,'Max');
[startframe,status] = str2num(get(src,'String'));
if (status)
    if (startframe < startmin) || (startframe > startmax)
        msgbox('Start frame value out of range. Reset to minimum.')
        startframe = startmin;
        set(src,'Value',startmin);
        set(src,'String',num2str(startmin,'%d'));
    end
else
    msgbox('Non-numeric value for start frame.  Reset to minimum.');
    startframe = startmin;
    set(src,'Value',startmin);
    set(src,'String',num2str(startmin,'%d'));
end
set(src,'Value',startframe);
end

% -------------------------------------------------------------------------
% hfinishCallback -- finish frame edit box function. Display new value,
% update "value" field.
function hfinishCallback(src,evnt)

endmin = get(src,'Min');
endmax = get(src,'Max');
[endframe,status] = str2num(get(src,'String'));
if (status)
    if (endframe == 0)
% zero is used to cancel
    elseif (endframe < endmin) || (endframe > endmax)
        msgbox('End frame value out of range. Reset to maximum.')
        endframe = endmax;
        set(src,'Value',endmax);
        set(src,'String',num2str(endmax,'%d'));
    end
else
    msgbox('Non-numeric value for end frame.  Reset to maximum.');
    endframe = endmax;
    set(src,'Value',endmax);
    set(src,'String',num2str(endmax,'%d'));
    
end
set(src,'Value',endframe);
end

% -------------------------------------------------------------------------
% my_closereq -- close button function. Prompt, close if "yes", else do
% nothing
function my_closereq(src,evnt)
hmsg = msgbox('To cancel, set end frame to 0, then click Continue',...
    'Close');

        return;
end
% -------------------------------------------------------------------------
% selcbk -- radiobutton selection. Display button handle#, old value and
% new value.
function selcbk(source,eventdata)
% ftypes={ '.avi','.tif','.jpg'};
filetype = get(get(source,'SelectedObject'),'Tag');
set(source,'UserData',filetype); 
end
% -------------------------------------------------------------------------
% selcbk1 -- radiobutton selection. Display button handle#, old value and
% new value.
function selcbk1(source,eventdata)
% stypes={'moviemax','framemax','shift5','shift4','none'};
scaling = get(get(source,'SelectedObject'),'Tag');
set(source,'UserData',scaling); 
end