% OutFileGUI -- dialog for output filetype and frame range. 0=cancel.
function [pOut,fOut] = OutFileGUI(pDefault,fDefault)

% frame range and file type figure window
hOutFileFig = figure('MenuBar','none', 'Toolbar','none', ...
    'HandleVisibility', 'callback', ...
    'Position', [190,500,600,200], ...
    'Name', 'Output File Path and Filename Prefix', ...
    'NumberTitle','off', ...
    'Color', get(0,'defaultuicontrolbackgroundcolor'), ...
    'CloseRequestFcn',@myOutFile_closereq, ...
    'Userdata',1);
hfolderlabel = uicontrol('Parent', hOutFileFig, 'Style', 'text', ...
    'Units', 'characters', 'Position',[5 10 15 1.5],...
    'FontSize',10, ...
    'String','Folder: ', ...
    'BackgroundColor',get(0,'defaultuicontrolbackgroundcolor'), ...
    'HorizontalAlignment','right');
hdisplayfolder = uicontrol('Parent', hOutFileFig, 'Style', 'text',...
    'Position',[20 6 15 1.5]); %dummy initial value
hfolder = uicontrol('Parent', hOutFileFig, 'Style', 'edit', ...
    'Units', 'characters', 'Position',[20 10 50 1.5],...
    'Max', 4, 'Min', 0, ...
    'FontSize',10, ...
    'Callback',@hfolderCallback, ...
    'BackgroundColor',[1,1,1], ...
    'UserData',hdisplayfolder, ...
    'String',pDefault);
% On our computer platforms,
% Font Size: 10 and Units: characters
% with Position: [left bottom width height]
% will fit 1.4 * (width) characters per line
%   and require line height=1.5.
hfileprefixlabel = uicontrol('Parent', hOutFileFig, 'Style', 'text', ...
    'Units', 'characters', 'Position',[5 8 15 1.5],...
    'String','File Prefix: ', ...
    'FontSize',10, ...
    'BackgroundColor',get(0,'defaultuicontrolbackgroundcolor'), ...
    'HorizontalAlignment','right');
hfileprefix = uicontrol('Parent', hOutFileFig, 'Style', 'edit', ...
    'Units', 'characters', 'Position',[20 8 50 1.5],...
    'FontSize',10, ...
    'Max', 4, 'Min', 0, ...
    'Callback',@hfileprefixCallback, ...
    'BackgroundColor',[1,1,1], ...
    'String',fDefault);
hBrowseButton = uicontrol('Parent',hOutFileFig,'Style','pushbutton', ...
    'Units','characters',...
    'Position',[70 9.8 15 2], ...
    'String','Browse...',...
    'Callback',@hbrowseCallback,...
    'Value',1);

hContinueButton = uicontrol('Parent',hOutFileFig,'Style','pushbutton', ...
    'Units','characters',...
    'Position',[20 4 15 2], ...
    'String','Continue',...
    'Callback','uiresume(gcbf)');
pathout = pDefault;
set(hBrowseButton,'UserData',hfolder);
pos = get(hfolder,'Position');
maxchar=floor(pos(3)/1.4);
numnamelines = ceil(size(pDefault,2)/maxchar);
pos(4)=numnamelines*1.5;
set(hfolder,'Position',pos);

uiwait(hOutFileFig);

set(hOutFileFig,'CloseRequestFcn','closereq'); % restore default fcn
pOut = get(hfolder,'String');
fOut = get(hfileprefix,'String');
close(hOutFileFig);

return
end
% -------------------------------------------------------------------------
% hfolderCallback -- folder edit box function.
%
function hfolderCallback(src,evnt)

% error checking?

end

% -------------------------------------------------------------------------
% hfileprefixCallback -- file prefix edit box function.
%
function hfileprefixCallback(src,evnt)

% error checking?

end


% -------------------------------------------------------------------------
% hbrowseCallback -- browse button edit box function.
%
function hbrowseCallback(src,evnt)

hfolder = get(src,'UserData');
start_path = get(hfolder,'String');
dialog_title = 'Select Output Folder';
directory_name = uigetdir(start_path,dialog_title);
% check for cancelled by user (zero) here
if(directory_name==0)
    return;
end
set(hfolder,'String',directory_name);
pos = get(hfolder,'Position');
maxchar=floor(pos(3)/1.4);
numnamelines = ceil(size(directory_name,2)/maxchar);
pos(4)=numnamelines*1.5;
set(hfolder,'String',directory_name,'Position',pos);


end
% -------------------------------------------------------------------------
% my_closereq -- close button function. Prompt, close if "yes", else do
% nothing
function myOutFile_closereq(src,evnt)
hmsg = msgbox('To cancel, clear both edit boxes, then click Continue',...
    'Close');

        return
end

